apiVersion: v1
kind: ServiceAccount
metadata:
  name: data-plane
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: data-plane-session-runtime
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "get", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: data-plane-session-runtime
subjects:
  - kind: ServiceAccount
    name: data-plane
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: data-plane-session-runtime
